### ISSUE TITLE
Progress bar won't show on same line

### ISSUE THREAD

**Issue by alexzadeh** [8bitgentleman/roam-depot-todo-progress-bar#2]
Hi,

This is a great plugin, thanks. I have one issue, though -  I can't get the bar to be on the same line as the bullet and text. Is this a known issue? I've disabled all other extensions and it still happens.

![CleanShot 2023-10-17 at 12 30 24@2x](https://github.com/8bitgentleman/roam-depot-todo-progress-bar/assets/11060179/6388a367-6043-49a3-8c94-7ff25ff09fe1)

Thanks,

Alex

**Comment by 8bitgentleman** [comment]
Looks like you're missing some CSS somehow. Not sure why. You need to add this in a css code block on you `[[roam/css]]` page

```
.roam-block>span>div.dont-focus-block {
    display: inline-block;
}
```

**Comment by alexzadeh** [comment]
Hi, I added that but it hasn't helped.

I removed the extension and re-added it, then added the code you suggested as a css code block:
![Screenshot -FilterCo - MTV_2024-01-26 at 10 39 20](https://github.com/8bitgentleman/roam-depot-todo-progress-bar/assets/11060179/f652ad32-de81-496f-8c8e-40b2bbd5e03a)

Any ideas?

Thanks

**Comment by 8bitgentleman** [comment]
Looks like roam changed their HTML try this

```
.roam-block>span>span.dont-focus-block {
    display: inline-block;
}
```

**Comment by alexzadeh** [comment]
Amazing, that worked, thanks!

Is there a way to configure it so that the top-level block/checkbox is not included in the count? Ideally, I would like it to only display the checkboxes underneath it. This way, the progress bar is a representation of all the individual actions that make up the item I am tracking.

**Comment by 8bitgentleman** [comment]
No that's not possible right now unfortunately. Glad the css worked though
